services:
  customer-service-front:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.frontend
    image: customer-service-front:latest
    ports:
      - "3000:3000"
    restart: always
    container_name: customer-service-front
  customer-service-back:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.backend
    image: customer-service-back:latest
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials:ro
      - ~/.aws/config:/root/.aws/config:ro
      - ~/.aws/sso/cache:/root/.aws/sso/cache:rw  # Only make cache writable
    ports:
      - "8000:8000"
    restart: always
    container_name: customer-service-back