services:
  mongodb-customer-service-front:
    build:
      context: ./
      dockerfile: dockerfile.frontend
    image: vector-search-front:latest
    ports:
      - "3000:3000"
    restart: always
    container_name: customer-service-front
  mongodb-customer-service-back:
    build:
      context: ./
      dockerfile: dockerfile.backend
    image: vector-search-back:latest
    ports:
      - "8000:8000"
    restart: always
    container_name: customer-service-back