services:
  customer-service-front:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.frontend
    image: customer-service-front:latest
    ports:
      - "3000:3000"
    restart: always
    container_name: customer-service-front
  customer-service-back:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.backend
    image: customer-service-back:latest
    ports:
      - "8000:8000"
    restart: always
    container_name: customer-service-back